version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # create topic "messages" with 1 partition and 3 replicas and topic "alerts" with 1 partition and 2 replicas
      KAFKA_CREATE_TOPIC: "messages:1:3,alerts:1:2"